package token

import (
	"testing"

	"github.com/ghosind/go-assert"
)

func TestLookupIdent(t *testing.T) {
	a := assert.New(t)

	a.EqualNow(LookupIdent("arguments"), TOKEN_ARGUMENTS)
	a.EqualNow(LookupIdent("as"), TOKEN_AS)
	a.EqualNow(LookupIdent("async"), TOKEN_ASYNC)
	a.EqualNow(LookupIdent("await"), TOKEN_AWAIT)
	a.EqualNow(LookupIdent("break"), TOKEN_BREAK)
	a.EqualNow(LookupIdent("case"), TOKEN_CASE)
	a.EqualNow(LookupIdent("catch"), TOKEN_CATCH)
	a.EqualNow(LookupIdent("class"), TOKEN_CLASS)
	a.EqualNow(LookupIdent("const"), TOKEN_CONST)
	a.EqualNow(LookupIdent("continue"), TOKEN_CONTINUE)
	a.EqualNow(LookupIdent("debugger"), TOKEN_DEBUGGER)
	a.EqualNow(LookupIdent("default"), TOKEN_DEFAULT)
	a.EqualNow(LookupIdent("delete"), TOKEN_DELETE)
	a.EqualNow(LookupIdent("do"), TOKEN_DO)
	a.EqualNow(LookupIdent("else"), TOKEN_ELSE)
	a.EqualNow(LookupIdent("enum"), TOKEN_ENUM)
	a.EqualNow(LookupIdent("eval"), TOKEN_EVAL)
	a.EqualNow(LookupIdent("export"), TOKEN_EXPORT)
	a.EqualNow(LookupIdent("extends"), TOKEN_EXTENDS)
	a.EqualNow(LookupIdent("false"), TOKEN_FALSE)
	a.EqualNow(LookupIdent("finally"), TOKEN_FINALLY)
	a.EqualNow(LookupIdent("for"), TOKEN_FOR)
	a.EqualNow(LookupIdent("from"), TOKEN_FROM)
	a.EqualNow(LookupIdent("function"), TOKEN_FUNCTION)
	a.EqualNow(LookupIdent("get"), TOKEN_GET)
	a.EqualNow(LookupIdent("if"), TOKEN_IF)
	a.EqualNow(LookupIdent("implements"), TOKEN_IMPLEMENTS)
	a.EqualNow(LookupIdent("import"), TOKEN_IMPORT)
	a.EqualNow(LookupIdent("in"), TOKEN_IN)
	a.EqualNow(LookupIdent("instanceof"), TOKEN_INSTANCEOF)
	a.EqualNow(LookupIdent("interface"), TOKEN_INTERFACE)
	a.EqualNow(LookupIdent("let"), TOKEN_LET)
	a.EqualNow(LookupIdent("meta"), TOKEN_META)
	a.EqualNow(LookupIdent("new"), TOKEN_NEW)
	a.EqualNow(LookupIdent("null"), TOKEN_NULL)
	a.EqualNow(LookupIdent("of"), TOKEN_OF)
	a.EqualNow(LookupIdent("package"), TOKEN_PACKAGE)
	a.EqualNow(LookupIdent("private"), TOKEN_PRIVATE)
	a.EqualNow(LookupIdent("protected"), TOKEN_PROTECTED)
	a.EqualNow(LookupIdent("public"), TOKEN_PUBLIC)
	a.EqualNow(LookupIdent("return"), TOKEN_RETURN)
	a.EqualNow(LookupIdent("set"), TOKEN_SET)
	a.EqualNow(LookupIdent("static"), TOKEN_STATIC)
	a.EqualNow(LookupIdent("super"), TOKEN_SUPER)
	a.EqualNow(LookupIdent("switch"), TOKEN_SWITCH)
	a.EqualNow(LookupIdent("target"), TOKEN_TARGET)
	a.EqualNow(LookupIdent("this"), TOKEN_THIS)
	a.EqualNow(LookupIdent("throw"), TOKEN_THROW)
	a.EqualNow(LookupIdent("true"), TOKEN_TRUE)
	a.EqualNow(LookupIdent("try"), TOKEN_TRY)
	a.EqualNow(LookupIdent("typeof"), TOKEN_TYPEOF)
	a.EqualNow(LookupIdent("undefined"), TOKEN_UNDEFINED)
	a.EqualNow(LookupIdent("var"), TOKEN_VAR)
	a.EqualNow(LookupIdent("void"), TOKEN_VOID)
	a.EqualNow(LookupIdent("while"), TOKEN_WHILE)
	a.EqualNow(LookupIdent("with"), TOKEN_WITH)
	a.EqualNow(LookupIdent("yield"), TOKEN_YIELD)

	a.EqualNow(LookupIdent("notKeyword"), TOKEN_IDENTIFIER)
}
