package token

import (
	"testing"

	"github.com/ghosind/go-assert"
)

func TestTokenTypeString(t *testing.T) {
	a := assert.New(t)
	a.EqualNow(TOKEN_EOF.String(), "token<EOF>")
	a.EqualNow(TOKEN_LEFT_PAREN.String(), "token<(>")
	a.EqualNow(TOKEN_RIGHT_PAREN.String(), "token<)>")
	a.EqualNow(TOKEN_LEFT_BRACE.String(), "token<{>")
	a.EqualNow(TOKEN_RIGHT_BRACE.String(), "token<}>")
	a.EqualNow(TOKEN_LEFT_BRACKET.String(), "token<[>")
	a.EqualNow(TOKEN_RIGHT_BRACKET.String(), "token<]>")
	a.EqualNow(TOKEN_AND.String(), "token<&>")
	a.EqualNow(TOKEN_AND_AND.String(), "token<&&>")
	a.EqualNow(TOKEN_AND_AND_EQUAL.String(), "token<&&=>")
	a.EqualNow(TOKEN_AND_EQUAL.String(), "token<&=>")
	a.EqualNow(TOKEN_BANG.String(), "token<!>")
	a.EqualNow(TOKEN_BANG_EQUAL.String(), "token<!=>")
	a.EqualNow(TOKEN_BANG_EQUAL_EQUAL.String(), "token<!==>")
	a.EqualNow(TOKEN_COLON.String(), "token<:>")
	a.EqualNow(TOKEN_COMMA.String(), "token<,>")
	a.EqualNow(TOKEN_DOT.String(), "token<.>")
	a.EqualNow(TOKEN_DOT_DOT_DOT.String(), "token<...>")
	a.EqualNow(TOKEN_EQUAL.String(), "token<=>")
	a.EqualNow(TOKEN_EQUAL_EQUAL.String(), "token<==>")
	a.EqualNow(TOKEN_EQUAL_EQUAL_EQUAL.String(), "token<===>")
	a.EqualNow(TOKEN_GREATER.String(), "token<>>")
	a.EqualNow(TOKEN_GREATER_EQUAL.String(), "token<>=>")
	a.EqualNow(TOKEN_GREATER_GREATER.String(), "token<>>>")
	a.EqualNow(TOKEN_GREATER_GREATER_EQUAL.String(), "token<>>=>")
	a.EqualNow(TOKEN_GREATER_GREATER_GREATER.String(), "token<>>>>")
	a.EqualNow(TOKEN_GREATER_GREATER_GREATER_EQUAL.String(), "token<>>>=>")
	a.EqualNow(TOKEN_HASH.String(), "token<#>")
	a.EqualNow(TOKEN_HASH_BANG.String(), "token<#!>")
	a.EqualNow(TOKEN_HAT.String(), "token<^>")
	a.EqualNow(TOKEN_HAT_EQUAL.String(), "token<^=>")
	a.EqualNow(TOKEN_LESS.String(), "token<<>")
	a.EqualNow(TOKEN_LESS_EQUAL.String(), "token<<=>")
	a.EqualNow(TOKEN_LESS_LESS.String(), "token<<<>")
	a.EqualNow(TOKEN_LESS_LESS_EQUAL.String(), "token<<<=>")
	a.EqualNow(TOKEN_MINUS.String(), "token<->")
	a.EqualNow(TOKEN_MINUS_EQUAL.String(), "token<-=>")
	a.EqualNow(TOKEN_MINUS_MINUS.String(), "token<-->")
	a.EqualNow(TOKEN_PERCENT.String(), "token<%>")
	a.EqualNow(TOKEN_PERCENT_EQUAL.String(), "token<%=>")
	a.EqualNow(TOKEN_PIPE.String(), "token<|>")
	a.EqualNow(TOKEN_PIPE_EQUAL.String(), "token<|=>")
	a.EqualNow(TOKEN_PIPE_PIPE.String(), "token<||>")
	a.EqualNow(TOKEN_PIPE_PIPE_EQUAL.String(), "token<||=>")
	a.EqualNow(TOKEN_PLUS.String(), "token<+>")
	a.EqualNow(TOKEN_PLUS_EQUAL.String(), "token<+=>")
	a.EqualNow(TOKEN_PLUS_PLUS.String(), "token<++>")
	a.EqualNow(TOKEN_QUESTION.String(), "token<?>")
	a.EqualNow(TOKEN_QUESTION_DOT.String(), "token<?.>")
	a.EqualNow(TOKEN_QUESTION_QUESTION.String(), "token<??>")
	a.EqualNow(TOKEN_QUESTION_QUESTION_EQUAL.String(), "token<??=>")
	a.EqualNow(TOKEN_SEMICOLON.String(), "token<;>")
	a.EqualNow(TOKEN_SLASH.String(), "token</>")
	a.EqualNow(TOKEN_SLASH_EQUAL.String(), "token</=>")
	a.EqualNow(TOKEN_STAR.String(), "token<*>")
	a.EqualNow(TOKEN_STAR_EQUAL.String(), "token<*=>")
	a.EqualNow(TOKEN_STAR_STAR.String(), "token<**>")
	a.EqualNow(TOKEN_STAR_STAR_EQUAL.String(), "token<**=>")
	a.EqualNow(TOKEN_TILDE.String(), "token<~>")
	a.EqualNow(TOKEN_IDENTIFIER.String(), "token<identifier>")
	a.EqualNow(TOKEN_STRING.String(), "token<string>")
	a.EqualNow(TOKEN_NUMBER.String(), "token<number>")
	a.EqualNow(TOKEN_ARGUMENTS.String(), "token<arguments>")
	a.EqualNow(TOKEN_AS.String(), "token<as>")
	a.EqualNow(TOKEN_ASYNC.String(), "token<async>")
	a.EqualNow(TOKEN_AWAIT.String(), "token<await>")
	a.EqualNow(TOKEN_BREAK.String(), "token<break>")
	a.EqualNow(TOKEN_CASE.String(), "token<case>")
	a.EqualNow(TOKEN_CATCH.String(), "token<catch>")
	a.EqualNow(TOKEN_CLASS.String(), "token<class>")
	a.EqualNow(TOKEN_CONST.String(), "token<const>")
	a.EqualNow(TOKEN_CONTINUE.String(), "token<continue>")
	a.EqualNow(TOKEN_DEBUGGER.String(), "token<debugger>")
	a.EqualNow(TOKEN_DEFAULT.String(), "token<default>")
	a.EqualNow(TOKEN_DELETE.String(), "token<delete>")
	a.EqualNow(TOKEN_DO.String(), "token<do>")
	a.EqualNow(TOKEN_ELSE.String(), "token<else>")
	a.EqualNow(TOKEN_ENUM.String(), "token<enum>")
	a.EqualNow(TOKEN_EVAL.String(), "token<eval>")
	a.EqualNow(TOKEN_EXPORT.String(), "token<export>")
	a.EqualNow(TOKEN_EXTENDS.String(), "token<extends>")
	a.EqualNow(TOKEN_FALSE.String(), "token<false>")
	a.EqualNow(TOKEN_FINALLY.String(), "token<finally>")
	a.EqualNow(TOKEN_FOR.String(), "token<for>")
	a.EqualNow(TOKEN_FROM.String(), "token<from>")
	a.EqualNow(TOKEN_FUNCTION.String(), "token<function>")
	a.EqualNow(TOKEN_GET.String(), "token<get>")
	a.EqualNow(TOKEN_IF.String(), "token<if>")
	a.EqualNow(TOKEN_IMPLEMENTS.String(), "token<implements>")
	a.EqualNow(TOKEN_IMPORT.String(), "token<import>")
	a.EqualNow(TOKEN_IN.String(), "token<in>")
	a.EqualNow(TOKEN_INSTANCEOF.String(), "token<instanceof>")
	a.EqualNow(TOKEN_INTERFACE.String(), "token<interface>")
	a.EqualNow(TOKEN_LET.String(), "token<let>")
	a.EqualNow(TOKEN_META.String(), "token<meta>")
	a.EqualNow(TOKEN_NEW.String(), "token<new>")
	a.EqualNow(TOKEN_NULL.String(), "token<null>")
	a.EqualNow(TOKEN_OF.String(), "token<of>")
	a.EqualNow(TOKEN_PACKAGE.String(), "token<package>")
	a.EqualNow(TOKEN_PRIVATE.String(), "token<private>")
	a.EqualNow(TOKEN_PROTECTED.String(), "token<protected>")
	a.EqualNow(TOKEN_PUBLIC.String(), "token<public>")
	a.EqualNow(TOKEN_RETURN.String(), "token<return>")
	a.EqualNow(TOKEN_SET.String(), "token<set>")
	a.EqualNow(TOKEN_STATIC.String(), "token<static>")
	a.EqualNow(TOKEN_SUPER.String(), "token<super>")
	a.EqualNow(TOKEN_SWITCH.String(), "token<switch>")
	a.EqualNow(TOKEN_TARGET.String(), "token<target>")
	a.EqualNow(TOKEN_THIS.String(), "token<this>")
	a.EqualNow(TOKEN_THROW.String(), "token<throw>")
	a.EqualNow(TOKEN_TRUE.String(), "token<true>")
	a.EqualNow(TOKEN_TRY.String(), "token<try>")
	a.EqualNow(TOKEN_TYPEOF.String(), "token<typeof>")
	a.EqualNow(TOKEN_UNDEFINED.String(), "token<undefined>")
	a.EqualNow(TOKEN_VAR.String(), "token<var>")
	a.EqualNow(TOKEN_VOID.String(), "token<void>")
	a.EqualNow(TOKEN_WHILE.String(), "token<while>")
	a.EqualNow(TOKEN_WITH.String(), "token<with>")
	a.EqualNow(TOKEN_YIELD.String(), "token<yield>")
	a.EqualNow(TOKEN_NEW_LINE.String(), "token<newline>")
	a.EqualNow(TOKEN_SPACE.String(), "token<space>")
	a.EqualNow(TOKEN_SINGLE_LINE_COMMENT.String(), "token<comment>")
	a.EqualNow(TOKEN_MULTI_LINE_COMMENT.String(), "token<comment>")
}

func TestInvalidTokenTypeString(t *testing.T) {
	a := assert.New(t)
	a.EqualNow(TokenType(999).String(), "token<unknown 999>")
	a.EqualNow(TokenType(-1).String(), "token<unknown -1>")
}
